version: "3.8"
services:
  frontend:
    container_name: weather-app
    build:
      context: .
      target: dev
    restart: always
    command: yarn dev
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
